require("dotenv").config();
const express=require("express"),session=require("express-session"),SQLiteStore=require("connect-sqlite3")(session),DB=require("better-sqlite3"),bcrypt=require("bcryptjs"),helmet=require("helmet"),multer=require("multer"),crypto=require("crypto"),fs=require("fs"),path=require("path");
const app=express(),db=new DB("fib.sqlite"),PORT=process.env.PORT||3000,MASTER=process.env.MASTER_DISCORD_ID||"1096326379064283218";
fs.mkdirSync("uploads",{recursive:true});db.pragma("journal_mode=WAL");
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,username TEXT UNIQUE,password_hash TEXT,discord_id TEXT UNIQUE,display_name TEXT,role TEXT DEFAULT 'agent',permissions TEXT DEFAULT '[]');
CREATE TABLE IF NOT EXISTS cases(id INTEGER PRIMARY KEY,case_no TEXT UNIQUE,title TEXT,category TEXT,status TEXT,priority TEXT,summary TEXT,assigned_to TEXT,created_by INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS evidence(id INTEGER PRIMARY KEY,evidence_no TEXT UNIQUE,case_id INTEGER,title TEXT,description TEXT,filename TEXT,original_name TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS employees(id INTEGER PRIMARY KEY,name TEXT,rank TEXT,department TEXT,status TEXT,notes TEXT);
CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY,actor TEXT,action TEXT,detail TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
app.use(helmet({contentSecurityPolicy:false}));app.use(express.urlencoded({extended:true}));app.use(session({store:new SQLiteStore({db:"sessions.sqlite",dir:"."}),secret:process.env.SESSION_SECRET||"CHANGE-ME",resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:"lax",secure:process.env.COOKIE_SECURE==="true",maxAge:28800000}}));
const all=(s,...a)=>db.prepare(s).all(...a),one=(s,...a)=>db.prepare(s).get(...a),run=(s,...a)=>db.prepare(s).run(...a);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function auth(req,res,next){if(!req.session.uid)return res.redirect("/login");req.user=one("SELECT * FROM users WHERE id=?",req.session.uid);if(!req.user)return res.redirect("/login");req.user.permissions=JSON.parse(req.user.permissions||"[]");next()}
function can(req,p){return req.user.role==="master"||req.user.role==="admin"||req.user.permissions.includes("*")||req.user.permissions.includes(p)}
function gate(p){return(req,res,next)=>can(req,p)?next():res.status(403).send("Zugriff verweigert")}
function audit(req,a,d=""){run("INSERT INTO audit(actor,action,detail) VALUES(?,?,?)",req.user?.display_name||"System",a,String(d))}
function page(req,title,body){return `<!doctype html><html lang="de"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${esc(title)} | FIB</title><link rel="stylesheet" href="/style.css"><header><b>FIB <small>INTERNAL</small></b>${req?.user?`<nav><a href="/">Dashboard</a><a href="/cases">Akten</a><a href="/evidence">Beweise</a><a href="/employees">Mitarbeiter</a>${can(req,"users")?'<a href="/users">Benutzer</a>':''}${req.user.role==="master"?'<a href="/master">Master</a>':''}</nav><span>${esc(req.user.display_name)} · <a href="/logout">Abmelden</a></span>`:""}</header><main><h1>${esc(title)}</h1>${body}</main><footer>FIB RP Aktenverwaltung · Community-Projekt</footer></html>`}
function formCase(c={}){return `<section><form method="post" action="/cases"><label>Titel<input name="title" required value="${esc(c.title)}"></label><label>Kategorie<input name="category" value="${esc(c.category||"Ermittlung")}"></label><label>Status<select name="status">${["Offen","In Bearbeitung","Abgeschlossen","Archiviert"].map(x=>`<option ${c.status===x?"selected":""}>${x}</option>`)}</select></label><label>Priorität<select name="priority">${["Niedrig","Normal","Hoch","Dringend"].map(x=>`<option ${c.priority===x?"selected":""}>${x}</option>`)}</select></label><label>Zuständig<input name="assigned_to" value="${esc(c.assigned_to)}"></label><label>Zusammenfassung<textarea name="summary">${esc(c.summary)}</textarea></label><button>Speichern</button></form></section>`}
function caseRows(rows){return `<table><tr><th>Aktenzeichen</th><th>Titel</th><th>Status</th><th>Priorität</th></tr>${rows.map(c=>`<tr><td><a href="/cases/${c.id}">${esc(c.case_no)}</a></td><td>${esc(c.title)}</td><td>${esc(c.status)}</td><td>${esc(c.priority)}</td></tr>`).join("")}</table>`}
app.get("/style.css",(r,s)=>s.type("text/css").send(fs.readFileSync("style.css")));
app.get("/login",(r,s)=>s.send(page(null,"Anmeldung",`<section class="login"><p>FIB · SECURE ACCESS</p><form method="post"><label>Benutzername<input name="username" required></label><label>Passwort<input type="password" name="password" required></label><button>Anmelden</button></form>${process.env.DISCORD_CLIENT_ID?'<p><a href="/auth/discord">Mit Discord anmelden</a></p>':""}<small>Master-Ersteinrichtung siehe README.</small></section>`)));
app.post("/login",(r,s)=>{let u=one("SELECT * FROM users WHERE username=?",r.body.username);if(!u||!bcrypt.compareSync(r.body.password,u.password_hash||"$2a$10$invalidinvalidinvalidinvalidinvalidinvalidinvalidinvalid"))return s.status(401).send(page(null,"Login fehlgeschlagen",'<a href="/login">Zurück</a>'));r.session.uid=u.id;audit({user:u},"Login");s.redirect("/")});
app.get("/logout",(r,s)=>r.session.destroy(()=>s.redirect("/login")));
app.get("/auth/discord",(r,s)=>{if(!process.env.DISCORD_CLIENT_ID)return s.status(503).send("Discord OAuth nicht eingerichtet");let state=crypto.randomBytes(16).toString("hex");r.session.oauthState=state;let u=new URL("https://discord.com/oauth2/authorize");Object.entries({client_id:process.env.DISCORD_CLIENT_ID,redirect_uri:process.env.DISCORD_CALLBACK_URL,response_type:"code",scope:"identify",state}).forEach(([k,v])=>u.searchParams.set(k,v));s.redirect(u.toString())});
app.get("/auth/discord/callback",async(r,s)=>{try{if(r.query.state!==r.session.oauthState)throw Error();let t=await fetch("https://discord.com/api/oauth2/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:process.env.DISCORD_CLIENT_ID,client_secret:process.env.DISCORD_CLIENT_SECRET,grant_type:"authorization_code",code:r.query.code,redirect_uri:process.env.DISCORD_CALLBACK_URL})});let token=await t.json();let me=await fetch("https://discord.com/api/users/@me",{headers:{Authorization:"Bearer "+token.access_token}});let d=await me.json(),u=one("SELECT * FROM users WHERE discord_id=?",d.id);if(!u&&d.id===MASTER){let ins=run("INSERT INTO users(username,password_hash,discord_id,display_name,role,permissions) VALUES(?,?,?,?,?,?)","discord_"+d.id,bcrypt.hashSync(crypto.randomBytes(32).toString("hex"),12),d.id,d.global_name||d.username,"master",'["*"]');u=one("SELECT * FROM users WHERE id=?",ins.lastInsertRowid)}if(!u)return s.status(403).send("Discord-Account nicht freigeschaltet");r.session.uid=u.id;audit({user:u},"Discord Login",d.id);s.redirect("/")}catch(e){s.status(400).send("Discord OAuth fehlgeschlagen; Einstellungen prüfen.")}});
app.get("/",auth,(r,s)=>s.send(page(r,"Dashboard",`<div class="stats"><section>Akten<strong>${one("SELECT count(*) n FROM cases").n}</strong></section><section>Offen<strong>${one("SELECT count(*) n FROM cases WHERE status='Offen'").n}</section><section>Beweise<strong>${one("SELECT count(*) n FROM evidence").n}</section><section>Mitarbeiter<strong>${one("SELECT count(*) n FROM employees").n}</section></div><section><h2>Letzte Akten</h2><a class="btn" href="/cases/new">+ Neue Akte</a>${caseRows(all("SELECT * FROM cases ORDER BY id DESC LIMIT 8"))}</section>`)));
app.get("/cases",auth,(r,s)=>{let term=r.query.q||"",rows=term?all("SELECT * FROM cases WHERE title LIKE ? OR case_no LIKE ? ORDER BY id DESC","%"+term+"%","%"+term+"%"):all("SELECT * FROM cases ORDER BY id DESC");s.send(page(r,"Akten",`<section><form class="search"><input name="q" placeholder="Suchen..." value="${esc(term)}"><button>Suchen</button></form><a class="btn" href="/cases/new">+ Neue Akte</a>${caseRows(rows)}</section>`))});
app.get("/cases/new",auth,gate("cases"),(r,s)=>s.send(page(r,"Neue Akte",formCase())));
app.post("/cases",auth,gate("cases"),(r,s)=>{let no="FIB-"+new Date().getFullYear()+"-"+Date.now().toString().slice(-6);let x=run("INSERT INTO cases(case_no,title,category,status,priority,summary,assigned_to,created_by) VALUES(?,?,?,?,?,?,?,?)",no,r.body.title,r.body.category,r.body.status,r.body.priority,r.body.summary,r.body.assigned_to,r.user.id);audit(r,"Akte erstellt",no);s.redirect("/cases/"+x.lastInsertRowid)});
app.get("/cases/:id",auth,(r,s)=>{let c=one("SELECT * FROM cases WHERE id=?",r.params.id);if(!c)return s.status(404).send("Nicht gefunden");let ev=all("SELECT * FROM evidence WHERE case_id=? ORDER BY id DESC",c.id);s.send(page(r,c.case_no,`<section><h2>${esc(c.title)}</h2><p>${esc(c.summary)}</p><p>Status: ${esc(c.status)} · Priorität: ${esc(c.priority)} · Zuständig: ${esc(c.assigned_to)}</p><a class="btn" href="/evidence/new?case_id=${c.id}">+ Beweis hinzufügen</a></section><section><h2>Beweise</h2>${ev.map(e=>`<article><b>${esc(e.evidence_no)} · ${esc(e.title)}</b><p>${esc(e.description)}</p>${e.filename?`<a href="/uploads/${encodeURIComponent(e.filename)}" target="_blank">${esc(e.original_name)}</a>`:""}</article>`).join("")||"Keine Beweise."}</section>`))});
const upload=multer({dest:"uploads/",limits:{fileSize:15*1024*1024},fileFilter:(r,f,cb)=>cb(null,[".png",".jpg",".jpeg",".pdf",".txt",".mp4",".webm",".zip"].includes(path.extname(f.originalname).toLowerCase()))});
app.get("/uploads/:file",auth,(r,s)=>{let f=path.basename(r.params.file);s.sendFile(path.join(__dirname,"uploads",f))});
app.get("/evidence",auth,(r,s)=>s.send(page(r,"Beweisregister",`<section><a class="btn" href="/evidence/new">+ Beweis erfassen</a><table><tr><th>Nr.</th><th>Titel</th><th>Akte</th><th>Datei</th></tr>${all("SELECT e.*,c.case_no FROM evidence e LEFT JOIN cases c ON c.id=e.case_id ORDER BY e.id DESC").map(e=>`<tr><td>${esc(e.evidence_no)}</td><td>${esc(e.title)}<small>${esc(e.description)}</small></td><td>${esc(e.case_no||"—")}</td><td>${e.filename?`<a href="/uploads/${encodeURIComponent(e.filename)}">${esc(e.original_name)}</a>`:"—"}</td></tr>`).join("")}</table></section>`)));
app.get("/evidence/new",auth,gate("evidence"),(r,s)=>s.send(page(r,"Beweis erfassen",`<section><form method="post" enctype="multipart/form-data"><label>Titel<input name="title" required></label><label>Akte<select name="case_id"><option value="">Nicht zugeordnet</option>${all("SELECT * FROM cases ORDER BY id DESC").map(c=>`<option value="${c.id}" ${String(c.id)===String(r.query.case_id)?"selected":""}>${esc(c.case_no)} · ${esc(c.title)}</option>`)}</select></label><label>Beschreibung<textarea name="description"></textarea></label><label>Datei (max 15 MB)<input type="file" name="file"></label><button>Speichern</button></form></section>`)));
app.post("/evidence",auth,gate("evidence"),upload.single("file"),(r,s)=>{let no="BEW-"+Date.now().toString().slice(-8);run("INSERT INTO evidence(evidence_no,case_id,title,description,filename,original_name) VALUES(?,?,?,?,?,?)",no,r.body.case_id||null,r.body.title,r.body.description,r.file?.filename||null,r.file?.originalname||null);audit(r,"Beweis erfasst",no);s.redirect("/evidence")});
// fix form target to the evidence route
app.get("/employees",auth,(r,s)=>s.send(page(r,"Mitarbeiter",`<section>${can(r,"employees")?'<a class="btn" href="/employees/new">+ Mitarbeiter</a>':""}<table><tr><th>Name</th><th>Dienstgrad</th><th>Abteilung</th><th>Status</th><th>Notizen</th></tr>${all("SELECT * FROM employees ORDER BY name").map(e=>`<tr><td>${esc(e.name)}</td><td>${esc(e.rank)}</td><td>${esc(e.department)}</td><td>${esc(e.status)}</td><td>${esc(e.notes)}</td></tr>`).join("")}</table></section>`)));
app.get("/employees/new",auth,gate("employees"),(r,s)=>s.send(page(r,"Mitarbeiter hinzufügen",`<section><form method="post"><label>Name<input name="name" required></label><label>Dienstgrad<input name="rank"></label><label>Abteilung<input name="department" value="FIB"></label><label>Status<select name="status"><option>Aktiv</option><option>Beurlaubt</option><option>Inaktiv</option></select></label><label>Notizen<textarea name="notes"></textarea></label><button>Speichern</button></form></section>`)));
app.post("/employees",auth,gate("employees"),(r,s)=>{run("INSERT INTO employees(name,rank,department,status,notes) VALUES(?,?,?,?,?)",r.body.name,r.body.rank,r.body.department,r.body.status,r.body.notes);audit(r,"Mitarbeiter hinzugefügt",r.body.name);s.redirect("/employees")});
app.get("/users",auth,gate("users"),(r,s)=>s.send(page(r,"Benutzer",`<section><a class="btn" href="/users/new">+ Benutzer</a><table><tr><th>Name</th><th>Discord-ID</th><th>Rolle</th><th>Rechte</th></tr>${all("SELECT * FROM users").map(u=>`<tr><td>${esc(u.display_name)}<small>${esc(u.username)}</small></td><td>${esc(u.discord_id)}</td><td>${esc(u.role)}</td><td>${esc(u.permissions)}</td></tr>`).join("")}</table></section>`)));
app.get("/users/new",auth,gate("users"),(r,s)=>s.send(page(r,"Benutzer anlegen",`<section><form method="post"><label>Name<input name="display_name" required></label><label>Benutzername<input name="username" required></label><label>Passwort (min. 12 Zeichen)<input type="password" name="password" minlength="12" required></label><label>Discord-ID optional<input name="discord_id"></label><label>Rolle<select name="role"><option>agent</option><option>supervisor</option><option>admin</option></select></label><fieldset>${["cases","evidence","employees","users"].map(p=>`<label><input type="checkbox" name="permissions" value="${p}"> ${p}</label>`).join("")}</fieldset><button>Erstellen</button></form></section>`)));
app.post("/users",auth,gate("users"),(r,s)=>{let ps=Array.isArray(r.body.permissions)?r.body.permissions:r.body.permissions?[r.body.permissions]:[];try{run("INSERT INTO users(username,password_hash,discord_id,display_name,role,permissions) VALUES(?,?,?,?,?,?)",r.body.username,bcrypt.hashSync(r.body.password,12),r.body.discord_id||null,r.body.display_name,r.body.role,JSON.stringify(ps));audit(r,"Benutzer erstellt",r.body.username);s.redirect("/users")}catch(e){s.status(400).send("Benutzername/Discord-ID bereits vergeben.")}});
app.get("/master",auth,(r,s)=>{if(r.user.role!=="master")return s.status(403).send("Nur Master");s.send(page(r,"Master Control",`<section class="notice">Master Discord-ID: ${esc(MASTER)}. Rollen und Rechte pro Benutzer verwalten.</section><section><h2>Benutzerrechte</h2><table><tr><th>Account</th><th>Rolle</th><th>Rechte (JSON-Array)</th><th></th></tr>${all("SELECT * FROM users").map(u=>`<tr><form method="post" action="/master/${u.id}"><td>${esc(u.display_name)}<small>${esc(u.discord_id||u.username)}</small></td><td><select name="role">${["agent","supervisor","admin","master"].map(x=>`<option ${u.role===x?"selected":""}>${x}</option>`)}</select></td><td><input name="permissions" value='${esc(u.permissions)}'></td><td><button>Speichern</button></td></form></tr>`).join("")}</table></section><section><h2>Audit-Protokoll</h2><table><tr><th>Zeit</th><th>Benutzer</th><th>Aktion</th><th>Details</th></tr>${all("SELECT * FROM audit ORDER BY id DESC LIMIT 100").map(a=>`<tr><td>${esc(a.created_at)}</td><td>${esc(a.actor)}</td><td>${esc(a.action)}</td><td>${esc(a.detail)}</td></tr>`).join("")}</table></section>`))});
app.post("/master/:id",auth,(r,s)=>{if(r.user.role!=="master")return s.status(403).send("Nur Master");let p;try{p=JSON.parse(r.body.permissions);if(!Array.isArray(p))throw Error()}catch{return s.status(400).send("Rechte müssen JSON-Array sein.")}if(+r.params.id===r.user.id&&r.body.role!=="master")return s.status(400).send("Eigenen Master nicht entfernen");run("UPDATE users SET role=?,permissions=? WHERE id=?",r.body.role,JSON.stringify(p),r.params.id);audit(r,"Rechte geändert",r.params.id);s.redirect("/master")});
app.listen(PORT,()=>console.log("FIB läuft auf http://localhost:"+PORT));
